const cardsInformation = [
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
  {
    name: "Grandma's Rice, Beans and Pork Chops.",
    source: "Grandma",
    category: "Dinner",
    description: "This my grandma's old recipe past down to her from her Mom and now to me.",
    ingredients: "Rice, beans and pork.",
    instructions: "Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
  },
];

export { cardsInformation };
